# Set update schedule for GitHub Actions
# See https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot

version: 2
enable-beta-ecosystems: true
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"

- package-ecosystem: "pub"
  directory: "/"
  schedule:
    interval: "weekly"
