# https://dart.dev/guides/language/analysis-options
include: package:lints/recommended.yaml

analyzer:
  errors:
    # These should be fixed or ignored in the proto generator
    implementation_imports: ignore
    no_leading_underscores_for_local_identifiers: ignore

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - omit_local_variable_types
    - prefer_final_locals
    - prefer_single_quotes
    - test_types_in_equals
    - use_super_parameters
