name: Publish
permissions:
  id-token: write
  pull-requests: write
on:
  pull_request:
    branches: [ master ]
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
jobs:
  publish:
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
