# A CI configuration to auto-publish pub packages.

name: Publish

on:
  pull_request:
    branches: [ master ]
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  publish:
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    with:
      write-comments: false
    permissions:
      id-token: write
      pull-requests: write
