name: Publish
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
on:
  pull_request:
    branches: [ master ]
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
jobs:
  publish:
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
